name: rust
base: core18
version: 1.35.0
license: Apache-2.0 AND MIT
summary: Rust programming language compiler, linker and other tools
description: |
  Rust is a multi-paradigm system programming language focused on safety,
  especially safe concurrency. Rust is syntactically similar to C++,
  but is designed to provide better memory safety while maintaining high performance.
  .
  This snap provides cargo and rustc.

grade: devel
confinement: strict

apps:
  cargo:
    command: bin/cargo
    completer: etc/bash_completion.d/cargo
    plugs:
      - home
      - network
  rustc:
    command: bin/rustc
    plugs:
      - home

layout:
  # rustc is looking there for static libraries
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET

parts:
  rust:
    plugin: nil
    source:
      - on amd64: https://static.rust-lang.org/dist/rust-$SNAPCRAFT_PROJECT_VERSION-x86_64-unknown-linux-gnu.tar.gz
      - on i386: https://static.rust-lang.org/dist/rust-$SNAPCRAFT_PROJECT_VERSION-i686-unknown-linux-gnu.tar.gz
      - on armhf: https://static.rust-lang.org/dist/rust-$SNAPCRAFT_PROJECT_VERSION-arm-unknown-linux-gnueabihf.tar.gz
      - on arm64: https://static.rust-lang.org/dist/rust-$SNAPCRAFT_PROJECT_VERSION-aarch64-unknown-linux-gnu.tar.gz
      - on s390x: https://static.rust-lang.org/dist/rust-$SNAPCRAFT_PROJECT_VERSION-s390x-unknown-linux-gnu.tar.gz
      - on ppc64el: https://static.rust-lang.org/dist/rust-$SNAPCRAFT_PROJECT_VERSION-powerpc64le-unknown-linux-gnu.tar.gz
    stage-packages:
      - gcc
      - libgcc1
      - libc6-dev
    override-build: |
      ln -s gcc $SNAPCRAFT_PART_INSTALL/usr/bin/cc
      ./install.sh \
        --destdir=$SNAPCRAFT_PART_INSTALL \
        --prefix=/ \
        --without=rust-docs,llvm-tools-preview,rustfmt-preview,miri-preview,clippy-preview,rls-preview
    prime:
      - -share/man
      - -share/doc
      - -usr/share/doc
      - -usr/share/lintian
      - -usr/share/man
